// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UniCareer.SimpleAPI.Data;

#nullable disable

namespace CVGenius_AI.Migrations
{
    [DbContext(typeof(CvContext))]
    [Migration("20260724134849_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UniCareer.SimpleAPI.Models.CvEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("KullaniciId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Yetenekler")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Özet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Cvler");
                });

            modelBuilder.Entity("UniCareer.SimpleAPI.Models.Deneyim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BaslangicTarihi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BitisTarihi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CvEntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Pozisyon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sirket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CvEntityId");

                    b.ToTable("Deneyimler");
                });

            modelBuilder.Entity("UniCareer.SimpleAPI.Models.Eğitim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BaşlangıcTarihi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BitisTarihi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bolum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CvEntityId")
                        .HasColumnType("integer");

                    b.Property<string>("OkulAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ortlama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CvEntityId");

                    b.ToTable("Eğitimler");
                });

            modelBuilder.Entity("UniCareer.SimpleAPI.Models.Kullanici", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("UniCareer.SimpleAPI.Models.Projeler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CvEntityId")
                        .HasColumnType("integer");

                    b.Property<string>("ProjeAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CvEntityId");

                    b.ToTable("Projeler");
                });

            modelBuilder.Entity("UniCareer.SimpleAPI.Models.Sertifikalar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AlisTarihi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BitisTarihi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CvEntityId")
                        .HasColumnType("integer");

                    b.Property<string>("SertifikaAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VerenKurum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CvEntityId");

                    b.ToTable("Sertifikalar");
                });

            modelBuilder.Entity("UniCareer.SimpleAPI.Models.CvEntity", b =>
                {
                    b.HasOne("UniCareer.SimpleAPI.Models.Kullanici", "Kullanici")
                        .WithMany("Cvler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("UniCareer.SimpleAPI.Models.Deneyim", b =>
                {
                    b.HasOne("UniCareer.SimpleAPI.Models.CvEntity", null)
                        .WithMany("Deneyim")
                        .HasForeignKey("CvEntityId");
                });

            modelBuilder.Entity("UniCareer.SimpleAPI.Models.Eğitim", b =>
                {
                    b.HasOne("UniCareer.SimpleAPI.Models.CvEntity", null)
                        .WithMany("Eğitim")
                        .HasForeignKey("CvEntityId");
                });

            modelBuilder.Entity("UniCareer.SimpleAPI.Models.Projeler", b =>
                {
                    b.HasOne("UniCareer.SimpleAPI.Models.CvEntity", null)
                        .WithMany("Projeler")
                        .HasForeignKey("CvEntityId");
                });

            modelBuilder.Entity("UniCareer.SimpleAPI.Models.Sertifikalar", b =>
                {
                    b.HasOne("UniCareer.SimpleAPI.Models.CvEntity", null)
                        .WithMany("Sertifikalar")
                        .HasForeignKey("CvEntityId");
                });

            modelBuilder.Entity("UniCareer.SimpleAPI.Models.CvEntity", b =>
                {
                    b.Navigation("Deneyim");

                    b.Navigation("Eğitim");

                    b.Navigation("Projeler");

                    b.Navigation("Sertifikalar");
                });

            modelBuilder.Entity("UniCareer.SimpleAPI.Models.Kullanici", b =>
                {
                    b.Navigation("Cvler");
                });
#pragma warning restore 612, 618
        }
    }
}
